/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserIndexRouteImport } from './routes/user/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as UserLeaderboardIndexRouteImport } from './routes/user/leaderboard/index'
import { Route as UserLanguageIndexRouteImport } from './routes/user/language/index'
import { Route as UserDashboardIndexRouteImport } from './routes/user/dashboard/index'
import { Route as UserAchievementsIndexRouteImport } from './routes/user/achievements/index'
import { Route as AdminLanguageIndexRouteImport } from './routes/admin/language/index'
import { Route as AdminDashboardIndexRouteImport } from './routes/admin/dashboard/index'
import { Route as UserLanguageLangCodeIndexRouteImport } from './routes/user/language/$langCode/index'
import { Route as AdminLanguageLangCodeIndexRouteImport } from './routes/admin/language/$langCode/index'
import { Route as UserLanguageLangCodeScenariosIndexRouteImport } from './routes/user/language/$langCode/scenarios/index'
import { Route as UserLanguageLangCodeFoundationIndexRouteImport } from './routes/user/language/$langCode/foundation/index'
import { Route as UserLanguageLangCodeAiConversionIndexRouteImport } from './routes/user/language/$langCode/ai-conversion/index'
import { Route as AdminLanguageLangCodeScenariosIndexRouteImport } from './routes/admin/language/$langCode/scenarios/index'
import { Route as AdminLanguageLangCodeFoundationIndexRouteImport } from './routes/admin/language/$langCode/foundation/index'
import { Route as AdminLanguageLangCodeAiConversionIndexRouteImport } from './routes/admin/language/$langCode/ai-conversion/index'
import { Route as UserLanguageLangCodeFoundationStagesLessonIdRouteImport } from './routes/user/language/$langCode/foundation/stages.$lessonId'
import { Route as UserLanguageLangCodeFoundationStageStageIdRouteImport } from './routes/user/language/$langCode/foundation/stage.$stageId'
import { Route as AdminLanguageLangCodeFoundationLessonLessonIdIndexRouteImport } from './routes/admin/language/$langCode/foundation/lesson.$lessonId/index'
import { Route as AdminLanguageLangCodeFoundationLessonLessonIdStageStageIdIndexRouteImport } from './routes/admin/language/$langCode/foundation/lesson.$lessonId/stage.$stageId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIndexRoute = UserIndexRouteImport.update({
  id: '/user/',
  path: '/user/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserLeaderboardIndexRoute = UserLeaderboardIndexRouteImport.update({
  id: '/user/leaderboard/',
  path: '/user/leaderboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserLanguageIndexRoute = UserLanguageIndexRouteImport.update({
  id: '/user/language/',
  path: '/user/language/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserDashboardIndexRoute = UserDashboardIndexRouteImport.update({
  id: '/user/dashboard/',
  path: '/user/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserAchievementsIndexRoute = UserAchievementsIndexRouteImport.update({
  id: '/user/achievements/',
  path: '/user/achievements/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLanguageIndexRoute = AdminLanguageIndexRouteImport.update({
  id: '/admin/language/',
  path: '/admin/language/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardIndexRoute = AdminDashboardIndexRouteImport.update({
  id: '/admin/dashboard/',
  path: '/admin/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserLanguageLangCodeIndexRoute =
  UserLanguageLangCodeIndexRouteImport.update({
    id: '/user/language/$langCode/',
    path: '/user/language/$langCode/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminLanguageLangCodeIndexRoute =
  AdminLanguageLangCodeIndexRouteImport.update({
    id: '/admin/language/$langCode/',
    path: '/admin/language/$langCode/',
    getParentRoute: () => rootRouteImport,
  } as any)
const UserLanguageLangCodeScenariosIndexRoute =
  UserLanguageLangCodeScenariosIndexRouteImport.update({
    id: '/user/language/$langCode/scenarios/',
    path: '/user/language/$langCode/scenarios/',
    getParentRoute: () => rootRouteImport,
  } as any)
const UserLanguageLangCodeFoundationIndexRoute =
  UserLanguageLangCodeFoundationIndexRouteImport.update({
    id: '/user/language/$langCode/foundation/',
    path: '/user/language/$langCode/foundation/',
    getParentRoute: () => rootRouteImport,
  } as any)
const UserLanguageLangCodeAiConversionIndexRoute =
  UserLanguageLangCodeAiConversionIndexRouteImport.update({
    id: '/user/language/$langCode/ai-conversion/',
    path: '/user/language/$langCode/ai-conversion/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminLanguageLangCodeScenariosIndexRoute =
  AdminLanguageLangCodeScenariosIndexRouteImport.update({
    id: '/admin/language/$langCode/scenarios/',
    path: '/admin/language/$langCode/scenarios/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminLanguageLangCodeFoundationIndexRoute =
  AdminLanguageLangCodeFoundationIndexRouteImport.update({
    id: '/admin/language/$langCode/foundation/',
    path: '/admin/language/$langCode/foundation/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminLanguageLangCodeAiConversionIndexRoute =
  AdminLanguageLangCodeAiConversionIndexRouteImport.update({
    id: '/admin/language/$langCode/ai-conversion/',
    path: '/admin/language/$langCode/ai-conversion/',
    getParentRoute: () => rootRouteImport,
  } as any)
const UserLanguageLangCodeFoundationStagesLessonIdRoute =
  UserLanguageLangCodeFoundationStagesLessonIdRouteImport.update({
    id: '/user/language/$langCode/foundation/stages/$lessonId',
    path: '/user/language/$langCode/foundation/stages/$lessonId',
    getParentRoute: () => rootRouteImport,
  } as any)
const UserLanguageLangCodeFoundationStageStageIdRoute =
  UserLanguageLangCodeFoundationStageStageIdRouteImport.update({
    id: '/user/language/$langCode/foundation/stage/$stageId',
    path: '/user/language/$langCode/foundation/stage/$stageId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminLanguageLangCodeFoundationLessonLessonIdIndexRoute =
  AdminLanguageLangCodeFoundationLessonLessonIdIndexRouteImport.update({
    id: '/admin/language/$langCode/foundation/lesson/$lessonId/',
    path: '/admin/language/$langCode/foundation/lesson/$lessonId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminLanguageLangCodeFoundationLessonLessonIdStageStageIdIndexRoute =
  AdminLanguageLangCodeFoundationLessonLessonIdStageStageIdIndexRouteImport.update(
    {
      id: '/admin/language/$langCode/foundation/lesson/$lessonId/stage/$stageId/',
      path: '/admin/language/$langCode/foundation/lesson/$lessonId/stage/$stageId/',
      getParentRoute: () => rootRouteImport,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/': typeof AdminIndexRoute
  '/user/': typeof UserIndexRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
  '/admin/language/': typeof AdminLanguageIndexRoute
  '/user/achievements/': typeof UserAchievementsIndexRoute
  '/user/dashboard/': typeof UserDashboardIndexRoute
  '/user/language/': typeof UserLanguageIndexRoute
  '/user/leaderboard/': typeof UserLeaderboardIndexRoute
  '/admin/language/$langCode/': typeof AdminLanguageLangCodeIndexRoute
  '/user/language/$langCode/': typeof UserLanguageLangCodeIndexRoute
  '/admin/language/$langCode/ai-conversion/': typeof AdminLanguageLangCodeAiConversionIndexRoute
  '/admin/language/$langCode/foundation/': typeof AdminLanguageLangCodeFoundationIndexRoute
  '/admin/language/$langCode/scenarios/': typeof AdminLanguageLangCodeScenariosIndexRoute
  '/user/language/$langCode/ai-conversion/': typeof UserLanguageLangCodeAiConversionIndexRoute
  '/user/language/$langCode/foundation/': typeof UserLanguageLangCodeFoundationIndexRoute
  '/user/language/$langCode/scenarios/': typeof UserLanguageLangCodeScenariosIndexRoute
  '/user/language/$langCode/foundation/stage/$stageId': typeof UserLanguageLangCodeFoundationStageStageIdRoute
  '/user/language/$langCode/foundation/stages/$lessonId': typeof UserLanguageLangCodeFoundationStagesLessonIdRoute
  '/admin/language/$langCode/foundation/lesson/$lessonId/': typeof AdminLanguageLangCodeFoundationLessonLessonIdIndexRoute
  '/admin/language/$langCode/foundation/lesson/$lessonId/stage/$stageId/': typeof AdminLanguageLangCodeFoundationLessonLessonIdStageStageIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminIndexRoute
  '/user': typeof UserIndexRoute
  '/admin/dashboard': typeof AdminDashboardIndexRoute
  '/admin/language': typeof AdminLanguageIndexRoute
  '/user/achievements': typeof UserAchievementsIndexRoute
  '/user/dashboard': typeof UserDashboardIndexRoute
  '/user/language': typeof UserLanguageIndexRoute
  '/user/leaderboard': typeof UserLeaderboardIndexRoute
  '/admin/language/$langCode': typeof AdminLanguageLangCodeIndexRoute
  '/user/language/$langCode': typeof UserLanguageLangCodeIndexRoute
  '/admin/language/$langCode/ai-conversion': typeof AdminLanguageLangCodeAiConversionIndexRoute
  '/admin/language/$langCode/foundation': typeof AdminLanguageLangCodeFoundationIndexRoute
  '/admin/language/$langCode/scenarios': typeof AdminLanguageLangCodeScenariosIndexRoute
  '/user/language/$langCode/ai-conversion': typeof UserLanguageLangCodeAiConversionIndexRoute
  '/user/language/$langCode/foundation': typeof UserLanguageLangCodeFoundationIndexRoute
  '/user/language/$langCode/scenarios': typeof UserLanguageLangCodeScenariosIndexRoute
  '/user/language/$langCode/foundation/stage/$stageId': typeof UserLanguageLangCodeFoundationStageStageIdRoute
  '/user/language/$langCode/foundation/stages/$lessonId': typeof UserLanguageLangCodeFoundationStagesLessonIdRoute
  '/admin/language/$langCode/foundation/lesson/$lessonId': typeof AdminLanguageLangCodeFoundationLessonLessonIdIndexRoute
  '/admin/language/$langCode/foundation/lesson/$lessonId/stage/$stageId': typeof AdminLanguageLangCodeFoundationLessonLessonIdStageStageIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/': typeof AdminIndexRoute
  '/user/': typeof UserIndexRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
  '/admin/language/': typeof AdminLanguageIndexRoute
  '/user/achievements/': typeof UserAchievementsIndexRoute
  '/user/dashboard/': typeof UserDashboardIndexRoute
  '/user/language/': typeof UserLanguageIndexRoute
  '/user/leaderboard/': typeof UserLeaderboardIndexRoute
  '/admin/language/$langCode/': typeof AdminLanguageLangCodeIndexRoute
  '/user/language/$langCode/': typeof UserLanguageLangCodeIndexRoute
  '/admin/language/$langCode/ai-conversion/': typeof AdminLanguageLangCodeAiConversionIndexRoute
  '/admin/language/$langCode/foundation/': typeof AdminLanguageLangCodeFoundationIndexRoute
  '/admin/language/$langCode/scenarios/': typeof AdminLanguageLangCodeScenariosIndexRoute
  '/user/language/$langCode/ai-conversion/': typeof UserLanguageLangCodeAiConversionIndexRoute
  '/user/language/$langCode/foundation/': typeof UserLanguageLangCodeFoundationIndexRoute
  '/user/language/$langCode/scenarios/': typeof UserLanguageLangCodeScenariosIndexRoute
  '/user/language/$langCode/foundation/stage/$stageId': typeof UserLanguageLangCodeFoundationStageStageIdRoute
  '/user/language/$langCode/foundation/stages/$lessonId': typeof UserLanguageLangCodeFoundationStagesLessonIdRoute
  '/admin/language/$langCode/foundation/lesson/$lessonId/': typeof AdminLanguageLangCodeFoundationLessonLessonIdIndexRoute
  '/admin/language/$langCode/foundation/lesson/$lessonId/stage/$stageId/': typeof AdminLanguageLangCodeFoundationLessonLessonIdStageStageIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/'
    | '/user/'
    | '/admin/dashboard/'
    | '/admin/language/'
    | '/user/achievements/'
    | '/user/dashboard/'
    | '/user/language/'
    | '/user/leaderboard/'
    | '/admin/language/$langCode/'
    | '/user/language/$langCode/'
    | '/admin/language/$langCode/ai-conversion/'
    | '/admin/language/$langCode/foundation/'
    | '/admin/language/$langCode/scenarios/'
    | '/user/language/$langCode/ai-conversion/'
    | '/user/language/$langCode/foundation/'
    | '/user/language/$langCode/scenarios/'
    | '/user/language/$langCode/foundation/stage/$stageId'
    | '/user/language/$langCode/foundation/stages/$lessonId'
    | '/admin/language/$langCode/foundation/lesson/$lessonId/'
    | '/admin/language/$langCode/foundation/lesson/$lessonId/stage/$stageId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/user'
    | '/admin/dashboard'
    | '/admin/language'
    | '/user/achievements'
    | '/user/dashboard'
    | '/user/language'
    | '/user/leaderboard'
    | '/admin/language/$langCode'
    | '/user/language/$langCode'
    | '/admin/language/$langCode/ai-conversion'
    | '/admin/language/$langCode/foundation'
    | '/admin/language/$langCode/scenarios'
    | '/user/language/$langCode/ai-conversion'
    | '/user/language/$langCode/foundation'
    | '/user/language/$langCode/scenarios'
    | '/user/language/$langCode/foundation/stage/$stageId'
    | '/user/language/$langCode/foundation/stages/$lessonId'
    | '/admin/language/$langCode/foundation/lesson/$lessonId'
    | '/admin/language/$langCode/foundation/lesson/$lessonId/stage/$stageId'
  id:
    | '__root__'
    | '/'
    | '/admin/'
    | '/user/'
    | '/admin/dashboard/'
    | '/admin/language/'
    | '/user/achievements/'
    | '/user/dashboard/'
    | '/user/language/'
    | '/user/leaderboard/'
    | '/admin/language/$langCode/'
    | '/user/language/$langCode/'
    | '/admin/language/$langCode/ai-conversion/'
    | '/admin/language/$langCode/foundation/'
    | '/admin/language/$langCode/scenarios/'
    | '/user/language/$langCode/ai-conversion/'
    | '/user/language/$langCode/foundation/'
    | '/user/language/$langCode/scenarios/'
    | '/user/language/$langCode/foundation/stage/$stageId'
    | '/user/language/$langCode/foundation/stages/$lessonId'
    | '/admin/language/$langCode/foundation/lesson/$lessonId/'
    | '/admin/language/$langCode/foundation/lesson/$lessonId/stage/$stageId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
  UserIndexRoute: typeof UserIndexRoute
  AdminDashboardIndexRoute: typeof AdminDashboardIndexRoute
  AdminLanguageIndexRoute: typeof AdminLanguageIndexRoute
  UserAchievementsIndexRoute: typeof UserAchievementsIndexRoute
  UserDashboardIndexRoute: typeof UserDashboardIndexRoute
  UserLanguageIndexRoute: typeof UserLanguageIndexRoute
  UserLeaderboardIndexRoute: typeof UserLeaderboardIndexRoute
  AdminLanguageLangCodeIndexRoute: typeof AdminLanguageLangCodeIndexRoute
  UserLanguageLangCodeIndexRoute: typeof UserLanguageLangCodeIndexRoute
  AdminLanguageLangCodeAiConversionIndexRoute: typeof AdminLanguageLangCodeAiConversionIndexRoute
  AdminLanguageLangCodeFoundationIndexRoute: typeof AdminLanguageLangCodeFoundationIndexRoute
  AdminLanguageLangCodeScenariosIndexRoute: typeof AdminLanguageLangCodeScenariosIndexRoute
  UserLanguageLangCodeAiConversionIndexRoute: typeof UserLanguageLangCodeAiConversionIndexRoute
  UserLanguageLangCodeFoundationIndexRoute: typeof UserLanguageLangCodeFoundationIndexRoute
  UserLanguageLangCodeScenariosIndexRoute: typeof UserLanguageLangCodeScenariosIndexRoute
  UserLanguageLangCodeFoundationStageStageIdRoute: typeof UserLanguageLangCodeFoundationStageStageIdRoute
  UserLanguageLangCodeFoundationStagesLessonIdRoute: typeof UserLanguageLangCodeFoundationStagesLessonIdRoute
  AdminLanguageLangCodeFoundationLessonLessonIdIndexRoute: typeof AdminLanguageLangCodeFoundationLessonLessonIdIndexRoute
  AdminLanguageLangCodeFoundationLessonLessonIdStageStageIdIndexRoute: typeof AdminLanguageLangCodeFoundationLessonLessonIdStageStageIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/': {
      id: '/user/'
      path: '/user'
      fullPath: '/user/'
      preLoaderRoute: typeof UserIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/leaderboard/': {
      id: '/user/leaderboard/'
      path: '/user/leaderboard'
      fullPath: '/user/leaderboard/'
      preLoaderRoute: typeof UserLeaderboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/language/': {
      id: '/user/language/'
      path: '/user/language'
      fullPath: '/user/language/'
      preLoaderRoute: typeof UserLanguageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/dashboard/': {
      id: '/user/dashboard/'
      path: '/user/dashboard'
      fullPath: '/user/dashboard/'
      preLoaderRoute: typeof UserDashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/achievements/': {
      id: '/user/achievements/'
      path: '/user/achievements'
      fullPath: '/user/achievements/'
      preLoaderRoute: typeof UserAchievementsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/language/': {
      id: '/admin/language/'
      path: '/admin/language'
      fullPath: '/admin/language/'
      preLoaderRoute: typeof AdminLanguageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard/': {
      id: '/admin/dashboard/'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard/'
      preLoaderRoute: typeof AdminDashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/language/$langCode/': {
      id: '/user/language/$langCode/'
      path: '/user/language/$langCode'
      fullPath: '/user/language/$langCode/'
      preLoaderRoute: typeof UserLanguageLangCodeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/language/$langCode/': {
      id: '/admin/language/$langCode/'
      path: '/admin/language/$langCode'
      fullPath: '/admin/language/$langCode/'
      preLoaderRoute: typeof AdminLanguageLangCodeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/language/$langCode/scenarios/': {
      id: '/user/language/$langCode/scenarios/'
      path: '/user/language/$langCode/scenarios'
      fullPath: '/user/language/$langCode/scenarios/'
      preLoaderRoute: typeof UserLanguageLangCodeScenariosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/language/$langCode/foundation/': {
      id: '/user/language/$langCode/foundation/'
      path: '/user/language/$langCode/foundation'
      fullPath: '/user/language/$langCode/foundation/'
      preLoaderRoute: typeof UserLanguageLangCodeFoundationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/language/$langCode/ai-conversion/': {
      id: '/user/language/$langCode/ai-conversion/'
      path: '/user/language/$langCode/ai-conversion'
      fullPath: '/user/language/$langCode/ai-conversion/'
      preLoaderRoute: typeof UserLanguageLangCodeAiConversionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/language/$langCode/scenarios/': {
      id: '/admin/language/$langCode/scenarios/'
      path: '/admin/language/$langCode/scenarios'
      fullPath: '/admin/language/$langCode/scenarios/'
      preLoaderRoute: typeof AdminLanguageLangCodeScenariosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/language/$langCode/foundation/': {
      id: '/admin/language/$langCode/foundation/'
      path: '/admin/language/$langCode/foundation'
      fullPath: '/admin/language/$langCode/foundation/'
      preLoaderRoute: typeof AdminLanguageLangCodeFoundationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/language/$langCode/ai-conversion/': {
      id: '/admin/language/$langCode/ai-conversion/'
      path: '/admin/language/$langCode/ai-conversion'
      fullPath: '/admin/language/$langCode/ai-conversion/'
      preLoaderRoute: typeof AdminLanguageLangCodeAiConversionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/language/$langCode/foundation/stages/$lessonId': {
      id: '/user/language/$langCode/foundation/stages/$lessonId'
      path: '/user/language/$langCode/foundation/stages/$lessonId'
      fullPath: '/user/language/$langCode/foundation/stages/$lessonId'
      preLoaderRoute: typeof UserLanguageLangCodeFoundationStagesLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/language/$langCode/foundation/stage/$stageId': {
      id: '/user/language/$langCode/foundation/stage/$stageId'
      path: '/user/language/$langCode/foundation/stage/$stageId'
      fullPath: '/user/language/$langCode/foundation/stage/$stageId'
      preLoaderRoute: typeof UserLanguageLangCodeFoundationStageStageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/language/$langCode/foundation/lesson/$lessonId/': {
      id: '/admin/language/$langCode/foundation/lesson/$lessonId/'
      path: '/admin/language/$langCode/foundation/lesson/$lessonId'
      fullPath: '/admin/language/$langCode/foundation/lesson/$lessonId/'
      preLoaderRoute: typeof AdminLanguageLangCodeFoundationLessonLessonIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/language/$langCode/foundation/lesson/$lessonId/stage/$stageId/': {
      id: '/admin/language/$langCode/foundation/lesson/$lessonId/stage/$stageId/'
      path: '/admin/language/$langCode/foundation/lesson/$lessonId/stage/$stageId'
      fullPath: '/admin/language/$langCode/foundation/lesson/$lessonId/stage/$stageId/'
      preLoaderRoute: typeof AdminLanguageLangCodeFoundationLessonLessonIdStageStageIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminIndexRoute: AdminIndexRoute,
  UserIndexRoute: UserIndexRoute,
  AdminDashboardIndexRoute: AdminDashboardIndexRoute,
  AdminLanguageIndexRoute: AdminLanguageIndexRoute,
  UserAchievementsIndexRoute: UserAchievementsIndexRoute,
  UserDashboardIndexRoute: UserDashboardIndexRoute,
  UserLanguageIndexRoute: UserLanguageIndexRoute,
  UserLeaderboardIndexRoute: UserLeaderboardIndexRoute,
  AdminLanguageLangCodeIndexRoute: AdminLanguageLangCodeIndexRoute,
  UserLanguageLangCodeIndexRoute: UserLanguageLangCodeIndexRoute,
  AdminLanguageLangCodeAiConversionIndexRoute:
    AdminLanguageLangCodeAiConversionIndexRoute,
  AdminLanguageLangCodeFoundationIndexRoute:
    AdminLanguageLangCodeFoundationIndexRoute,
  AdminLanguageLangCodeScenariosIndexRoute:
    AdminLanguageLangCodeScenariosIndexRoute,
  UserLanguageLangCodeAiConversionIndexRoute:
    UserLanguageLangCodeAiConversionIndexRoute,
  UserLanguageLangCodeFoundationIndexRoute:
    UserLanguageLangCodeFoundationIndexRoute,
  UserLanguageLangCodeScenariosIndexRoute:
    UserLanguageLangCodeScenariosIndexRoute,
  UserLanguageLangCodeFoundationStageStageIdRoute:
    UserLanguageLangCodeFoundationStageStageIdRoute,
  UserLanguageLangCodeFoundationStagesLessonIdRoute:
    UserLanguageLangCodeFoundationStagesLessonIdRoute,
  AdminLanguageLangCodeFoundationLessonLessonIdIndexRoute:
    AdminLanguageLangCodeFoundationLessonLessonIdIndexRoute,
  AdminLanguageLangCodeFoundationLessonLessonIdStageStageIdIndexRoute:
    AdminLanguageLangCodeFoundationLessonLessonIdStageStageIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
